Olympic Games Data Transfer/Controllers/FavoriteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Olympic_Games_Data_Transfer.Models;
using System.Diagnostics.Metrics;

namespace Olympic_Games_Data_Transfer.Controllers
{
    public class FavoriteController : Controller
    {
        private CountryContext context;
        public FavoriteController(CountryContext ctx)
        {
            context = ctx;
        }

        [HttpGet]
        public ViewResult Index()
        {
            var session = new OlympicSession(HttpContext.Session);
            var model = new Models.CountryViewModel
            {
                ActiveEvent = session.GetActiveEvent(),
                ActiveSport = session.GetActiveSport(),
                countries = session.GetMyCountry()
            };
            return View(model);
        }

        [HttpPost]
        public RedirectToActionResult Add(Country country)
        {
            country = context.Countrys
                 .Include(t => t.events)
                 .Include(t => t.sport)
                 .Where(t => t.CountryID == country.CountryID)
                 .FirstOrDefault() ?? new Country();
            var session = new OlympicSession(HttpContext.Session);
            var cookies = new OlympicCookies(Response.Cookies);

            var countries = session.GetMyCountry();
            countries.Add(country);
            session.SetMyCountry(countries);
            cookies.SetMyCountryIds(countries);

            TempData["message"] = $"{country.CountryName} added to your favorites";
            return RedirectToAction("Index", "Home", 
                new
                {
                    ActiveEvent = session.GetActiveEvent(),
                    ActiveSport = session.GetActiveSport()
                });

        }

        [HttpPost]
        public RedirectToActionResult Delete()
        {
            var session = new OlympicSession(HttpContext.Session);
            var cookies = new OlympicCookies(Response.Cookies);

            session.RemoveMyCountry();
            cookies.RemoveMyCountryIds();

            TempData["message"] = $"Favorite countries cleared";
            return RedirectToAction("Index", "Home",
             new
             {
                 ActiveEvent = session.GetActiveEvent(),
                 ActiveSport = session.GetActiveSport()
             });
        }

    }
}

Olympic Games Data Transfer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Olympic_Games_Data_Transfer.Models;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Linq;

namespace Olympic_Games_Data_Transfer.Controllers
{
    public class HomeController : Controller
    {
        private CountryContext context;

        public HomeController(CountryContext ctx)
        {
            context = ctx;
        }


        
        public ViewResult Index(Models.CountryViewModel model)
        {
            var session = new OlympicSession(HttpContext.Session);
            session.setActiveEvent(model.ActiveEvent);
            session.setActiveSport(model.ActiveSport);
            int? count = session.GetMyCountryCount();
            if (!count.HasValue)
            {
                var cookies = new OlympicCookies(Request.Cookies);
                string[] ids = cookies.GetMyCountryIds();

                if(ids.Length > 0)
                {
                    var mycountries = context.Countrys
                         .Include(t => t.events)
                        .Include(t => t.sport)
                        .Where(t => ids.Contains(t.CountryID))
                        .ToList();
                    session.SetMyCountry(mycountries);
                }
            }

            model.events = context.Events.ToList();
            model.sports = context.Sports.ToList();

            IQueryable<Country> query = context.Countrys;



            if (model.ActiveEvent != "all")
            {
                query = query.Where(c => c.events.EventID.ToLower() == model.ActiveEvent.ToLower());

            }
            if (model.ActiveSport != "all")
            {
                query = query.Where(d => d.sport.SportID.ToLower() == model.ActiveSport.ToLower());
            }
            model.countries = query.ToList();
            return View(model);
        }

        public ViewResult Details(string id)
        {
            var session = new OlympicSession(HttpContext.Session);
            var model = new Models.CountryViewModel
            {
                Country = context.Countrys
                    .Include(t => t.events)
                    .Include(t => t.sport)
                    .FirstOrDefault(t => t.CountryID == id) ?? new Country(),
                ActiveEvent = session.GetActiveEvent(),
                ActiveSport = session.GetActiveSport()
            };
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Olympic Games Data Transfer/Views/Home/Details.cshtml
@model CountryViewModel
@{
    ViewData["Title"] = "Country Details";
}

<h2 class="text-center p-2">Team Details</h2>

<div class="row">
    <div class="col">
        <ul class="list-group text-center">
            <li class="list-group-item">
                <img src="~/images/@Model.Country.flag" alt=" " />
                <h3>@Model.Country.CountryName</h3>
            </li>
            <li class="list-group-item">
                <h4>Event: @Model.Country.events?.EventName</h4>
            </li>
            <li class="list-group-item">
                <h4>Sport: @Model.Country.sport?.SportName</h4>
            </li>
            <li class="list-group-item">
                <form asp-action="Add" asp-controller="Favorite" method="post">
                    <a asp-action="Index" class="btn btn-primary"
                        asp-route-activeEvent="@Model.ActiveEvent"
                        asp-route-activeSport="@Model.ActiveSport">Return to Home Page</a>
                        <button type="submit" class="btn btn-primary">Add to Favorites</button>
                        <input type="hidden" asp-for="Country.CountryID" />
                </form>
            </li>
        </ul>
    </div>
</div>

Olympic Games Data Transfer/Views/Home/Index.cshtml
@model CountryViewModel
@{
    ViewData["Title"] = "Olympic Games";
}

<div class="row">
    <div class="col-md-3">
        <h3 class="mt-3">Events</h3>
        <div class="list-group">
            <a asp-action="Index"
               asp-route-activeEvent="all"
               asp-route-activeSport="@Model.ActiveSport"
               class="list-group-item @Model.CheckActiveEvent("all")">All</a>

            @foreach (Event events in Model.events)
            {
                <a asp-action="Index"
                   asp-route-activeEvent="@events.EventID"
                   asp-route-activeSport="@Model.ActiveSport"
                   class="list-group-item @Model.CheckActiveEvent(events.EventName)">@events.EventName</a>
            }
        </div>

        <h3 class="mt-3">Sports</h3>
        <div class="list-group">
            <a asp-action="Index"
               asp-route-activeEvent="@Model.ActiveEvent"
               asp-route-activeSport="all"
               class="list-group-item @Model.CheckActiveSport("all")">All</a>

            @foreach (Sport sports in Model.sports)
            {
                <a asp-action="Index"
                   asp-route-activeEvent="@Model.ActiveEvent"
                   asp-route-activeSport="@sports.SportID"
                   class="list-group-item @Model.CheckActiveSport(sports.SportName)">@sports.SportName</a>
            }
        </div>
    </div>

    <div class="col-md-9">
        <ul class="list-inline">
            @foreach (Country country in Model.countries)
            {
                <li class="list-inline-item">
                    <a asp-action="Details" asp-route-id="@country.CountryID">
                    <img class="thumbnail img-responsive" src="~/images/@country.flag"
                         alt="@country.CountryName | @(country.events?.EventName ?? "No Event") | @(country.sport?.category ?? "No Sport")"
                         title="@country.CountryName | @(country.events?.EventName ?? "No Event") | @(country.sport?.category ?? "No Sport")" />
                    </a>

                </li>
            }
        </ul>
    </div>
</div>